### ISSUE TITLE
directory exists and overwrite files

### ISSUE THREAD

**Issue by Moealsir** [amasin76/intranet-chrome-extension#14]
**Describe the problem**

1. If the directory is exist it return error: `mkdir: cannot create directory ‘0x0E-structures_typedef’: File exists` and doesn't continue.
**Prefer fix:**
use command: `mkdir -p $directory && cd $directory` to create the directory or enter directory if found.

2. The given command is overwriting old files in the directory.
**prefer fix:**
Modify creating command to check and pass files that already exists and not empty and only create files that doesn't exist.

![Screenshot from 2024-01-13 17-46-46](https://github.com/amasin76/intranet-chrome-extension/assets/140074143/e6280e90-b773-446b-84eb-d0e8fa3cb9c3)

Adding those features will make your tool greater than before.

I appreciate this tool and i use it for daily alx tasks, thank you for such a great extension.

**Comment by amasin76** [comment]
Thanks for your detailed feedback, appreciate it 🙏

We understand the issues you've pointed out and your proposed fixes. we'll address these in our next update 🤍
