### ISSUE TITLE
Faster way to check

### ISSUE THREAD

**Issue by solomonchidera** [amasin76/intranet-chrome-extension#16]
**This is just a suggestion.**
A better way to check the answers for the quiz

**Can solve this by ctrl + Enter**
Faster checking of the quiz checker by pressing ctrl + enter using the keyboard can be a great feature to include in this awesome tool

**As described above**
Implementing a feature where you can use the keyboard to check the quiz question by pressing ctrl + Enter

**Shout Out to you guys**
This a great tool tbh, use it every day, especially for the mass creation of files, and the appending of the shebang line is just awesome

**Comment by amasin76** [comment]
I’m happy to hear that you find the extension useful. The shortcut suggestion of using `Ctrl + Enter` for faster quiz checking is indeed helpful 👍, and I’ll definitely consider adding it in the next update
